Feature/sr 14 implement checkout page
goscoot/scooter-reservation pull request #12
Opened 2023-05-15 11:28 UTC by GalacticOctopus

Page contains form, map and product components. We also have added Zustand to keep global state in check.

2023-05-15 16:16 UTC, masterHAWK99 requested changes

2023-05-23 16:36 UTC, GalacticOctopus commented on src/components/booking/BookingList.tsx
> +          onClick={() => formik.handleSubmit}
To my understanding `onClick={formik.handleSubmit}` secretly passes element's event for which we have no use. All that needs to happen is function executing.

2023-05-23 19:23 UTC, GalacticOctopus commented on src/scss/components/_square.scss
> +}
It's possible. The way it's done now allows us to configure the current dashed border in more ways than it's allowed by default.

2023-05-23 19:25 UTC, GalacticOctopus commented on src/pages/Booking.tsx
> +          values.paymentMethod = selectedPayment;
Values is what is going to be submitted and we need to set it's values to currently selected states.

2023-05-24 16:23 UTC, masterHAWK99 requested changes

2023-05-24 16:23 UTC, masterHAWK99 commented on src/components/booking/form/PaymentMethod.tsx
> +        <p className="text-caption text-weight-600">PayPal</p>
Those elements should be labels for radio fields above so users can choose payment method by clicking on name

2023-05-24 16:23 UTC, masterHAWK99 commented on src/components/map/PickLocationMap.tsx
> +type TPickLocationMapProps = {
You don't need prefix `T` if you have suffix `Props`.

2023-05-24 16:23 UTC, masterHAWK99 commented on src/components/booking/BookingItem.tsx
> +type TBookingItemProps = {
You don't need prefix `T` if you have suffix `Props`.

2023-05-24 18:25 UTC, merged