Feature/sr 10 implement hero section
goscoot/scooter-reservation pull request #3
Opened 2023-03-18 19:55 UTC by GalacticOctopus

Responsive Hero Page _(plus basic react router)_

2023-03-18 22:39 UTC, masterHAWK99 requested changes

2023-03-18 22:39 UTC, masterHAWK99 commented on src/App.tsx
> +          <Route path="/" element={<Navigate to="/home" />}></Route>
Homepage should be at `/` path.

2023-03-18 22:39 UTC, masterHAWK99 commented on src/scss/pages/_home.scss
> +}
Get rid of duplicated classess

2023-03-18 22:39 UTC, masterHAWK99 commented on src/scss/base/_typography.scss
> +.text-body-sm-bold {
Create separated class called for example: `text-700` for this font weight.

2023-03-18 22:39 UTC, masterHAWK99 commented on src/pages/Hero.tsx
> +            ></img>
Import those images

2023-03-18 22:44 UTC, masterHAWK99 requested changes

2023-03-18 22:44 UTC, masterHAWK99 commented on src/scss/pages/_home.scss
> +    background-color: #f7fcf5;
Use variables with colors

2023-03-18 22:44 UTC, masterHAWK99 commented on src/scss/pages/_home.scss
> +    background-color: #f9f9f9;
Use variables with colors

2023-03-19 12:09 UTC, GalacticOctopus commented on src/pages/Hero.tsx
> +            ></img>
You mean, by using props?

2023-03-23 20:48 UTC, masterHAWK99 approved these changes

2023-03-23 20:48 UTC, merged