Feature/sr 11 implement featured products section
goscoot/scooter-reservation pull request #4
Opened 2023-03-20 00:04 UTC by GalacticOctopus

+ featured page
+ functional slider (mobile responsive)

2023-03-20 00:07 UTC, GalacticOctopus commented
Three commits are from previous branch because I had to merge them. Please ignore them

2023-03-20 13:59 UTC, masterHAWK99 requested changes

2023-03-20 13:59 UTC, masterHAWK99 commented on src/components/Slider.tsx
> +    carouselRef.current.classList.add("dragging");
Change class name conditionally in JSX based on state instead modifying DOM like that.

2023-03-20 13:59 UTC, masterHAWK99 commented on src/components/Slider.tsx
> +  function handleTouchDown(event: React.TouchEvent<HTMLDivElement>) {
Import this interface directly, not from `React`.

2023-03-20 13:59 UTC, masterHAWK99 commented on src/components/Slider.tsx
> +                <img src="src\assets\arrow-right.svg" alt="Arrow right" />
Import this image

2023-03-20 13:59 UTC, masterHAWK99 commented on src/components/Slider.tsx
> +              <a href="/reservation" className="text-caption link-underlined">
Use `react-router` links

2023-03-20 13:59 UTC, masterHAWK99 commented on src/components/Slider.tsx
> +        {value.map((v) => (
Add unique id to each product and use it as value for `key` prop. Also use meaningful names, not `v`, `e` etc.

2023-03-20 13:59 UTC, masterHAWK99 commented on src/components/Slider.tsx
> +            if (carouselRef.current) carouselRef.current.scrollLeft += 325;
Create function for this operation.

2023-03-20 13:59 UTC, masterHAWK99 commented on src/pages/Featured.tsx
> +];
Add real products

2023-03-20 13:59 UTC, masterHAWK99 commented on src/pages/Featured.tsx
> +          </p>
Get rid of `br`'s

2023-03-20 13:59 UTC, masterHAWK99 commented on src/components/Slider.tsx
> +              <h2 className="text-700 text-body-sm">{v.title}</h2>
Use correct styling for title

2023-03-20 21:08 UTC, masterHAWK99 requested changes

2023-03-20 21:08 UTC, masterHAWK99 commented on src/components/Slider.tsx
> +export function Slider({ value }: SliderProps) {
Please move logic code to hook

2023-03-23 20:47 UTC, masterHAWK99 approved these changes

2023-03-23 20:48 UTC, merged