Feature/sr 20 firebase integration
goscoot/scooter-reservation pull request #5
Opened 2023-03-28 13:23 UTC by GalacticOctopus

- Add Firebase Auth and Firestore
- Create queries
- Attach to featured page

2023-03-28 16:07 UTC, mzajaczkowsky reviewed
Pull request adds Firebase to the project and updates the code of slider on Feature component.

2023-03-28 16:45 UTC, masterHAWK99 commented on src/hooks/useAuth.tsx
> +};
Please log potential errors by console.log, users don't have to see them everytime. What about checking if user is logged in?

2023-03-28 21:35 UTC, masterHAWK99 requested changes

2023-03-28 21:35 UTC, masterHAWK99 commented on src/hooks/useAuth.tsx
> +*/
Please don't leave commented code

2023-03-28 21:35 UTC, masterHAWK99 commented on src/hooks/useProducts.tsx
> +  const [productList, setProductList] = useState<any>([]);
Add correct type instead of `any`

2023-04-01 12:49 UTC, masterHAWK99 approved these changes

2023-04-01 15:02 UTC, merged