Feature/sr 9 implement sign in form
goscoot/scooter-reservation pull request #6
Opened 2023-03-28 14:46 UTC by mzajaczkowsky

- Add Sign In page
- Create Route /login for Sign In form

2023-03-28 16:30 UTC, masterHAWK99 requested changes

2023-03-28 16:30 UTC, masterHAWK99 commented on src/pages/Login.tsx
> +  const manageSubmit = (e: React.FormEvent<HTMLFormElement>): void => {
Use meaningful names, not `e`, also return type is redundant.

2023-03-28 16:30 UTC, masterHAWK99 commented on src/pages/Login.tsx
> +    console.log(`${email} | ${password}`);
Please get rid of that debug

2023-03-28 16:30 UTC, masterHAWK99 commented on src/pages/Login.tsx
> +  const [password, setPassword] = useState<string>("");
Type of these states are infered from inistial value, so generics are not necessary.

2023-03-28 16:30 UTC, masterHAWK99 commented on src/pages/Register.tsx
> +                onChange={(e) => setPassword(e.target.value)}
Same as in login, and shouldn't be state for name yet?

2023-03-28 16:30 UTC, masterHAWK99 commented on src/pages/Signin.tsx
> +}
The same navbar will be on all pages, so it should be implemented using `Outlet`, not here.

2023-03-28 16:30 UTC, masterHAWK99 commented on src/pages/Signup.tsx
> +  );
Same as Signin

2023-03-31 17:48 UTC, GalacticOctopus approved these changes
Looking good

2023-03-31 17:49 UTC, merged